[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "python3-dev", "build-essential"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn wsgi:application --bind 0.0.0.0:$PORT"
